#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define APP_NAME "CYD TURNTABLE"

#define PREFERENCES_NAMESPACE "CYD_PREFS"
#define PREFERENCES_KEY_LAUCH_COUNT "launch"
#define PREFERENCES_KEY_DOUBLE_RESET "dr"
#define ACCESS_POINT_NAME APP_NAME
#define ACCESS_POINT_PASSWORD "1234567890"

#define BACKGROUND_COLOUR TFT_BLACK
#define TEXT_COLOUR TFT_WHITE

#endif