#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define APP_NAME "BB Intercom"

#define PREFERENCES_NAMESPACE "BBI_PREFS"
#define PREFERENCES_KEY_CALIBRATED "cal"
#define PREFERENCES_KEY_TOP_LEFT_X "tlx"
#define PREFERENCES_KEY_TOP_LEFT_Y "tly"
#define PREFERENCES_KEY_TOP_RIGHT_X "trx"
#define PREFERENCES_KEY_TOP_RIGHT_Y "try"
#define PREFERENCES_KEY_BOTTOM_LEFT_X "blx"
#define PREFERENCES_KEY_BOTTOM_LEFT_Y "bly"
#define PREFERENCES_KEY_BOTTOM_RIGHT_X "brx"
#define PREFERENCES_KEY_BOTTOM_RIGHT_Y "bly"

#define BACKGROUND_COLOUR TFT_BLACK
#define TEXT_COLOUR TFT_WHITE

#define CROSSHAIR_COLOUR TFT_WHITE
#define CROSSHAIR_SIZE 30
#define CROSSHAIR_MARGIN 10

#define TOP_LEFT 1
#define TOP_RIGHT 2
#define BOTTOM_LEFT 3
#define BOTTOM_RIGHT 4


#endif